#!/bin/sh

#=================================================
# Nokia XG-040G 首次启动默认配置
#=================================================

#=================================================
# 主机名
#=================================================

uci set system.@system[0].hostname='OpenWrt'

#=================================================
# 日志
#=================================================

uci set system.@system[0].log_size='32'

#=================================================
# 删除旧 WAN / LAN 配置
#=================================================

uci -q delete network.wan
uci -q delete network.lan

# 删除旧 br-lan
uci -q delete network.br_lan

#=================================================
# WAN
# lan1 = WAN
#=================================================

uci set network.wan='interface'
uci set network.wan.device='lan1'
uci set network.wan.proto='dhcp'

#=================================================
# LAN
# lan2 / lan3 / lan4
#=================================================

uci set network.lan='interface'
uci set network.lan.device='br-lan'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='192.168.6.1'
uci set network.lan.netmask='255.255.255.0'

#=================================================
# br-lan
# 强制只包含 lan2 / lan3 / lan4
#=================================================

uci set network.br_lan='device'
uci set network.br_lan.type='bridge'

uci add_list network.br_lan.ports='lan2'
uci add_list network.br_lan.ports='lan3'
uci add_list network.br_lan.ports='lan4'

#=================================================
# 默认密码
#=================================================

(echo 'password'; sleep 1; echo 'password') | passwd root >/dev/null 2>&1

#=================================================
# Argon
#=================================================

uci set luci.main.mediaurlbase='/luci-static/argon'

#=================================================
# 默认语言：简体中文
#=================================================

uci set luci.main.lang='zh_cn'

#=================================================
# 提交配置
#=================================================

uci commit system
uci commit network
uci commit luci

#=================================================
# 最终检查
#=================================================

echo "==============================================="
echo " Nokia XG-040G 默认网络配置完成"
echo "==============================================="

echo "WAN:"
uci show network.wan

echo "LAN:"
uci show network.lan

echo "BR-LAN:"
uci show network.br_lan

echo "==============================================="

exit 0
