net.netfilter.nf_conntrack_max=16384

# TCP receive buffer
net.ipv4.tcp_rmem=4096 4194304 33554432

# TCP send buffer
net.ipv4.tcp_wmem=4096 1048576 33554432

# Maximum socket receive buffer
net.core.rmem_max=33554432

# Maximum socket send buffer
net.core.wmem_max=33554432

# TCP memory pressure thresholds
net.ipv4.tcp_mem=16384 24576 32768
